money-flow-api:
  springdoc:
    swagger-ui:
      enabled: true
  openapi-servers-urls: http://localhost:${server.port}${server.servlet.context-path}, http://127.0.0.1:${server.port}${server.servlet.context-path}